### ISSUE TITLE
Support `with.token`

### ISSUE THREAD

**Issue by fregante** [octokit/auth-action.js#104]
The most used first-party `actions/checkout` action uses the cleaner `token` input instead of the 60s-like `GITHUB_TOKEN`

https://github.com/actions/checkout#usage

Can this also automatically support `with.token` instead of just `GITHUB_TOKEN`?

```yml
steps:
  - name: My action
    with:
      token: ${{ secrets.GITHUB_TOKEN }}
```
