### ISSUE TITLE
[FEAT]: Support `with.github-token` (kebab-case)

### ISSUE THREAD

**Issue by DariuszPorowski** [octokit/auth-action.js#318]
### Describe the need

Following up https://github.com/octokit/auth-action.js/issues/104

A few first-party actions like:
- https://github.com/actions/add-to-project/blob/main/src/add-to-project.ts#L38
- https://github.com/actions/github-script/blob/main/src/main.ts#L27

uses kebab-case style for github token, on the community side much more ;)

Nice to have `with.github-token` support instead of only `with.token` or `with.github_token`, like:

```yaml
steps:
  - name: My action
    with:
      github-token: ${{ github.token }}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
